Feat: modify folder structure/ create register and login routes
codinBabe/ceaser_cipher pull request #1
Opened 2024-10-08 19:36 UTC by codinBabe

2024-10-11 16:34 UTC, adelajaOlamilekan commented on .gitignore
Good!

Rembering not to push .env and db

2024-10-11 16:38 UTC, codinBabe commented on .gitignore
ok boss

2024-10-11 17:06 UTC, adelajaOlamilekan requested changes

2024-10-11 17:06 UTC, adelajaOlamilekan commented on backend/app/api/v1/auth.py
Create access token should be done inside the user service file. Not exposed in your route.

Routes should only focus on getting input, calling a service and returning the output

2024-10-11 17:06 UTC, adelajaOlamilekan commented on backend/app/crud/user_crud.py
A Crud function should only focus on get, post, put and delete a resource.

It shouldn't do authentication or verifying of  password. These should be services.

2024-10-11 17:06 UTC, adelajaOlamilekan commented on backend/app/models/document_model.py
Document content shouldn't be in the database. It will take large space.

You should rather upload the document to a cloud service and store the link to the document in the database

2024-10-11 17:06 UTC, adelajaOlamilekan commented on backend/app/schemas/user_schema.py
UserCreate should have a confirm password field. Frontend can check it tho. Backend should still check it tho

UserResponse should have id, username,  date_created and date_updated.

2024-10-11 17:06 UTC, adelajaOlamilekan commented on backend/app/schemas/document_schema.py
DocumentResponse should have id, title, original_document_url, encrypted_document_url, date_created, date_updated.

2024-10-11 18:57 UTC, codinBabe commented on backend/app/models/document_model.py
Noted

2024-10-12 04:58 UTC, merged

2024-10-27 05:08 UTC, codinBabe commented on backend/app/api/v1/auth.py
Fixed

2024-10-27 05:08 UTC, codinBabe commented on backend/app/crud/user_crud.py
Fixed this also

2024-10-27 05:09 UTC, codinBabe commented on backend/app/schemas/document_schema.py
Corrected this also, I will push changes for review soon

2024-10-27 05:11 UTC, codinBabe commented on backend/app/schemas/user_schema.py
I intentionally skip this boss, since it is a very simple website but if you insist sha.